# Generated by Django 5.2.5 on 2025-08-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('завод', 'завод'), ('розничная сеть', 'розничная сеть'), ('индивидуальный предприниматель', 'индивидуальный предприниматель')], default='завод', max_length=50, verbose_name='Тип модели сети (по умолчанию Завод)')),
                ('name', models.CharField(blank=True, help_text='Введите название модели сети', max_length=100, null=True, verbose_name='Название модели сети')),
                ('hierarchy_level', models.CharField(choices=[('0', '0'), ('1', '0'), ('2', '1')], default='0', max_length=50, verbose_name='Иерархический уровень (определяется программой)')),
                ('Arrears', models.DecimalField(blank=True, decimal_places=2, help_text='Введите Задолженность', max_digits=12, null=True, verbose_name='Задолженность')),
                ('Creation_time', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netmodel.networkmodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.CharField(help_text='Введите email', max_length=100, verbose_name='email')),
                ('contact_country', models.CharField(blank=True, help_text='Введите название страны', max_length=100, null=True, verbose_name='Страна')),
                ('contact_city', models.CharField(blank=True, help_text='Введите название города', max_length=100, null=True, verbose_name='Город')),
                ('contact_street', models.CharField(blank=True, help_text='Введите название улицы', max_length=100, null=True, verbose_name='Улица')),
                ('contact_house_number', models.CharField(blank=True, help_text='Введите номер дома', max_length=100, null=True, verbose_name='Номер дома')),
                ('contact', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netmodel.networkmodel', verbose_name='Модель сети')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='Введите название продукта', max_length=100, null=True, verbose_name='Название продукта')),
                ('product_model', models.TextField(blank=True, help_text='Введите модель продукта', max_length=100, null=True, verbose_name='Модель продукта')),
                ('product_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода продукта на рынок')),
                ('network_model', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netmodel.networkmodel', verbose_name='Модель сети')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
