# Generated by Django 5.2.5 on 2025-08-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkmodel',
            old_name='Arrears',
            new_name='arrears',
        ),
        migrations.RenameField(
            model_name='networkmodel',
            old_name='Creation_time',
            new_name='creation_time',
        ),
        migrations.AddField(
            model_name='networkmodel',
            name='contact_city',
            field=models.CharField(blank=True, help_text='Введите название города', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='networkmodel',
            name='contact_country',
            field=models.CharField(blank=True, help_text='Введите название страны', max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='networkmodel',
            name='contact_email',
            field=models.CharField(blank=True, help_text='Введите email', max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='networkmodel',
            name='contact_house_number',
            field=models.CharField(blank=True, help_text='Введите номер дома', max_length=100, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='networkmodel',
            name='contact_street',
            field=models.CharField(blank=True, help_text='Введите название улицы', max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='networkmodel',
            name='hierarchy_level',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=50, verbose_name='Иерархический уровень (определяется программой)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_model',
            field=models.CharField(blank=True, help_text='Введите модель продукта', max_length=100, null=True, verbose_name='Модель продукта'),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
