# Generated by Django 5.2.5 on 2025-08-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmodel', '0002_rename_arrears_networkmodel_arrears_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmodel',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Укажите email', max_length=254, null=True, verbose_name='email'),
        ),
    ]
