# Generated by Django 5.2.5 on 2025-08-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmodel', '0003_alter_networkmodel_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='netmodel.networkmodel', verbose_name='Поставщик'),
        ),
    ]
