# Generated by Django 5.2.5 on 2025-08-22 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmodel', '0004_alter_networkmodel_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmodel',
            name='related_person',
            field=models.ForeignKey(blank=True, help_text='Автоматически заполняется данными текущего пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='netmodel', to=settings.AUTH_USER_MODEL, verbose_name='связанное с организацией лицо'),
        ),
        migrations.AlterField(
            model_name='networkmodel',
            name='hierarchy_level',
            field=models.CharField(default=0, verbose_name='Иерархический уровень (определяется программой)'),
        ),
    ]
