# Generated by Django 5.2.5 on 2025-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmodel', '0005_networkmodel_related_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmodel',
            name='hierarchy_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Иерархический уровень (определяется программой)'),
        ),
    ]
